buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://maven.minecraftforge.net/' }
        maven { url 'https://nexus.gtnewhorizons.com/repository/public/' }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:1.2.11.dirty'
    }
}

apply plugin: 'forge'

group = 'gcewing.sg'
version = '2.46.2-mc1.7.10-dev'
archivesBaseName = 'SGCraft'
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
    maven { url 'https://maven.minecraftforge.net/' }
    maven { url 'https://nexus.gtnewhorizons.com/repository/public/' }
    maven { url 'https://gregtech.mechaenetia.com/' }
}

dependencies {
    compileOnly 'dan200.computercraft:ComputerCraft:1.75'
    compileOnly 'li.cil.oc:OpenComputers:MC1.7.10-1.7.2.1204:dev'
    compileOnly 'cofh:CoFHCore:1.7.10R3.0.4:dev'
    compileOnly 'cofh:CoFHLib:1.7.10R3.0.3:dev'
    compileOnly 'ic2:IC2Classic:1.2.1.8:dev'
    testCompile 'junit:junit:4.13.2'
}

configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == 'org.scala-lang' && requested.name in ['scala-parser-combinators_2.11', 'scala-swing_2.11', 'scala-xml_2.11']) {
            useTarget "org.scala-lang.modules:${requested.name}:${requested.version}"
        }
    }
}

configurations.testRuntimeClasspath.extendsFrom configurations.compileOnly

minecraft {
    version = '1.7.10-10.13.4.1614-1.7.10'
    runDir = 'run'
}
